vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /img/plateformes
            upload_destination: '%kernel.project_dir%/public/img/plateformes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        article_image:
            uri_prefix: /img/articles
            upload_destination: '%kernel.project_dir%/public/img/articles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        document_file:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/public/documents'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
