language: php
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/symfony-bridge/.phpunit"
env:
  global:
  - PHPUNIT_FLAGS="-v"
  - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
  - ACTION=install
matrix:
  fast_finish: true
  include:
  # - php: 7.2
  - php: 7.4
deploy:
  provider: heroku
  api_key:
    secure: 03DyQWGxEUVCs8sysol0KIHH5CcUvO6LO8Nz5GdwsgKPUVUh91lFSNgdYk9dtfb+kbPRfrfwIcSYVi0rEQm9TqyY/lc/b4aTKGBnEdmRVvdD5UV3vaTKlVm+YGjKr/3Rfd79dhsNZmhNcDvU059SNK2wHYfjDmVCxjp7f+QAcfsnNhNgweXgp5sx1Lxr58eOmUVjL+u97+nLfA6I+yy90IU+4ZLpw1xOZ6WYljybKIy6SpklF3J5JnxBL0/xVbqA1C5/6eb6vbtGg21SQc7dTI9xRo+RC9g1J9NRqC+iEmY2y4+id9DjdPKrX6QXJc1SCkpAzkf4GGgTj4sAznnaGeOwjglWYSZLnKmD9gw1KnJ0X4+E5kZE0ICbyzLqobUoN+pa4eJdeYaDIw7V8aLxxnlD3C3wQpnxMxq/A+DJa0XKF3dM9ZyQCYsi5ExBkA6+ExezbZbYeN5eOIrk3xRxGxr98QKhC7i8tHeqvymUT3V1M7zuMl+mxs/JdkZrB9v0MsMh6W/pHc/K6ud+va1Ra6I2x0GO8ItNIoawOxezHBwChLdrM5Y+lDMFYpbqw/vxY7WRmGv0/jQxYcFkfyaGDLTlrQbFW5NBxILWgf4IzoEjn1Iegq0Y9fJqnWacIk+MHqYhCxz7n+L9ePa5mWn1iBIWJNQhVBPWjKiUm909j9s=
  app:
    production: rim-edu
  run:
    - "./bin/console doctrine:migrations:migrate --no-interaction"
    # - ./bin/phpunit
before_install:
  # - '[[ "$TRAVIS_PHP_VERSION" == "7.4snapshot" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
  # Set memory to max (memory fail)
  - '[[ "$ACTION" == "install" ]] || echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
  # Set stability to dev to allow 4.4dev and 5.0dev
  # - '[[ "$ACTION" == "install" ]] || composer config minimum-stability dev'
  # Change version of symfony when need
  - '[[ "$ACTION" == "install" ]] || composer config extra.symfony.require $SYMFONY'
install:
  - php -r "echo ini_get('memory_limit').PHP_EOL;"
  # install or update
  - composer $ACTION
  # - ./bin/phpunit install
script:
  # - ./bin/phpunit
  # this checks that the source code follows the Symfony Code Syntax rules
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config --parse-tags
  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig templates --env=prod
  # this checks that the XLIFF translations contain no syntax errors
  - ./bin/console lint:yaml translations
  # this checks that arguments injected into services match type declarations
  - ./bin/console lint:container

